# to use with vscode, install the extension REST Client extension

### get all
GET http://localhost:3000/message


### get one
GET http://localhost:3000/message/653

### create a message
POST http://localhost:3000/message
Content-Type: application/json

{
  "content": "super cool message"
}

